spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: daian0401
  jpa:
    show-sql: true
    jackson:
      default-property-inclusion: non_null
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
    static-path-pattern: /**
  resources:
    static-locations: classpath:/

server:
  servlet:
    context-path: /api
  port: 8080
my-config:
  prePassword: 888888
  key:
    locationIdNumber: 4 #locationId 的位数
    collectionIdNumber: 4 # collectId 的位数
    workIdNumber: 4 #员工工号后缀位数
    noticeIdNumber: 4 #公告id的位数
    signInIdNumber: 8 #用户每日签到数据id
